version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: url-shortener-pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    network_mode: "host"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    depends_on:
      - postgres
    network_mode: "host"

